### ISSUE TITLE
Add subPaths to route object

### ISSUE THREAD

**Issue by maximgatilin** [mono-js/mono#12]
It would be awesome to have this nested paths to avoid duplication, e.g. /users/foo and users/bar

<div align="right"><sub><em>This question is available on <a href="https://terrajs.cmty.io">Terra JS</a> community (<a href="https://terrajs.cmty.io/terrajs/mono/issues/c2">#c2</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hey @maximgatilin 

Thanks for the suggestion, could you give an example of how you would imagine using it with Mono?

**Comment by maximgatilin** [comment]
main route
```
const userSubPaths = require('./userSubPaths');
module.exports = [
  {
    method: 'GET',
    path: '/users',
    handler: controller.doSomething,
    subPaths: userSubPaths
  }
]
```
userSubPaths.js:
```
module.exports = [
  {
    method: 'GET',
    path: '/foo',
    handler: fooController.doSomething
  },
 {
    method: 'GET',
    path: '/bar',
    handler: barController.doSomething
  }
]
```

**Comment by Atinux** [comment]
Hi @maximgatilin 

After a discussion with the team, it does not seem right to have route in other files than `.routes.js`.

Actually, you may want to use some helper function:

```js
// users.routes.js
const { join }  = require('path')
const usersPath = (path) => join('/users', path || '')

module.exports = [
  {
    method: 'GET',
    path: usersPath(),
    handler: controller.doSomething,
    subPaths: userSubPaths
  },
  {
    method: 'GET',
    path: usersPath('/foo'),
    handler: fooController.doSomething
  },
 {
    method: 'GET',
    path: usersPath('/bar'),
    handler: barController.doSomething
  }
]
```

**Comment by maximgatilin** [comment]
LGTM
