### ISSUE TITLE
CORS Header Issue while deploying

### ISSUE THREAD

**Issue by antoineLZCH** [mono-js/mono#16]
Hi everyone,

Thanks a lot for your job. Mono seems really nice to build express servers.

We're in trouble with a friend :
We're doing a final-year-project, based on MonoJS Server and Ionic. The API is deployed on Heroku with the database on MongoDB Atlas.

When we try to register a new user in our application, we have an error based on cors headers : 

![cors issue](https://user-images.githubusercontent.com/37066803/50011161-a52da780-ffbb-11e8-8011-e8ac6b5aa3e9.png)

This is usually an error sent when the Headers are not defined, but we don't know how to import and use cors npm package properly, which we think it can resolve the issue.

We tried to create an init.js file based on what @Atinux told me, but is it better to create it on src/ folder ? How can Heroku know we want to use this file to active the headers ?

Thanks in advance. We're juniors, we still have a lot to learn !

Long lives Mono, long lives Nuxt !

**Comment by benjamincanac** [comment]
Hey @antoineLZCH,

You can check the documentation on init files [here](https://mono.js.org/#/init-files).

There is an example on how to setup CORS with init files.

This should solve your issue 🙂

**Comment by antoineLZCH** [comment]
Hi,

Damn, we didn't see that when we looked on the doc. 

I guess you can close this one!

Thank you so much. 

Have a great day, 

Antoine
